### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [kieraw/tc359-project11#1]
It doesn't look like my login information is working on Heroku. Did you add forget to add the user to Heroku's database?

**Comment by kieraw** [comment]
@chrisvfritz Yeah. How do you do that?

**Comment by chrisvfritz** [comment]
Just like we used the `rails console` to create a new user locally, we'll do the same thing on Heroku. To migrate the database on Heroku, we used `heroku run rake db:migrate`. To run the console on Heroku, follow the same pattern of prefixing the command with `heroku run`. :smiley: The final result being:

```
heroku run rails console
```

**Comment by kieraw** [comment]
@chrisvfritz Should be good now!

**Comment by chrisvfritz** [comment]
:+1: Looks great!
